[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test/foundry'
cache_path = 'cache/foundry'
solc_version = '0.8.19'
optimizer = true
optimizer_runs = 200
evm_version = 'paris'
via_ir = false
ffi = true

[profile.invariant]
optimizer = false
optimizer_runs = 1

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }